services:
  db:
    image: postgres:17
    container_name: learnhub-postgres
    environment:
      POSTGRES_DB: learnhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - learnhub-db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  learnhub-db-data:
